
[window]
opacity = 0.4
padding.x = 50
padding.y = 40

[colors]
transparent_background_colors = true

[colors.primary]
foreground = "#E0E2EA"
background = "#0B0E14"

[colors.normal]
black   = "#050508"
red     = "#FF5C5C"
green   = "#3DDB84"
yellow  = "#FFCC66"
blue    = "#7AA2F7"
magenta = "#B18CFE"
cyan    = "#97F1FB"
white   = "#E0E2EA"

[colors.bright]
black   = "#242B3D"
red     = "#FF8C42"
green   = "#3DDB84"
yellow  = "#FFCC66"
blue    = "#7AA2F7"
magenta = "#B18CFE"
cyan    = "#97F1FB"
white   = "#E0E2EA"

[colors.cursor]
text   = "#0B0E14"
cursor = "#FFCC66"
