# Background and foreground colors
foreground = #E0E2EA
background = #0B0E14
cursor-color = #FFCC66

background-opacity = 0.4
window-padding-x = 40
window-padding-y = 30

# Standard colors
palette = 0=#050508
palette = 1=#FF5C5C
palette = 2=#3DDB84
palette = 3=#FFCC66
palette = 4=#7AA2F7
palette = 5=#B18CFE
palette = 6=#97F1FB
palette = 7=#E0E2EA

# Bright colors
palette = 8=#242B3D
palette = 9=#FF8C42
palette = 10=#3DDB84
palette = 11=#FFCC66
palette = 12=#7AA2F7
palette = 13=#B18CFE
palette = 14=#97F1FB
palette = 15=#E0E2EA
