# Background and foreground colors
foreground = #E6E8F0
background = #0B0D14
cursor-color = #FFD27D

background-opacity = 0.4
window-padding-x = 40
window-padding-y = 30

# Standard colors
palette = 0=#05060A
palette = 1=#FF5C5C
palette = 2=#3DDB84
palette = 3=#F2C94C
palette = 4=#7AA2F7
palette = 5=#C099FF
palette = 6=#B4F9F8
palette = 7=#E6E8F0

# Bright colors
palette = 8=#23283B
palette = 9=#FF5C5C
palette = 10=#3DDB84
palette = 11=#F2C94C
palette = 12=#7AA2F7
palette = 13=#C099FF
palette = 14=#B4F9F8
palette = 15=#E6E8F0
