$color = rgba(11, 14, 20, 1.0)
$inner_color = rgba(22, 27, 41, 1.0)
$outer_color = rgba(255, 204, 102, 1.0)
$font_color = rgba(224, 226, 234, 1.0)
$check_color = rgba(61, 219, 132, 1.0)
#
background {
    monitor =
    # path = ~/.config/omarchy/themes/felix/backgrounds/03-Clouds.png
    # path = $HOME/.config/omarchy/current/background
  # Replace with the path to your image
    blur_passes = 0                  # Optional: Set to 0 for no blur, or higher for blur effect
    blur_size = 8                    # Optional: Size of blur, if enabled
    color = rgba(5, 5, 8, 0.5)    # Optional: Fallback color if image fails
}
