foreground            #E6E8F0
background            #0B0D14

background_opacity 0.5
window_padding_width 40
window_padding_height 20

# black
color0  #05060A
color8  #23283B

# red
color1  #FF5C5C
color9  #FF5C5C

# green
color2  #3DDB84
color10 #3DDB84

# yellow
color3  #F2C94C
color11 #F2C94C

# blue
color4  #7AA2F7
color12 #7AA2F7

# magenta
color5  #C099FF
color13 #C099FF

#cyan
color6  #B4F9F8
color14 #B4F9F8

#white
color7  #E6E8F0
color15 #E6E8F0

cursor #FFD27D
cursor_text_color #0B0D14
