foreground            #E0E2EA
background            #0B0E14

background_opacity 0.5
window_padding_width 40
window_padding_height 20

# black
color0  #050508
color8  #242B3D

# red
color1  #FF5C5C
color9  #FF8C42

# green
color2  #3DDB84
color10 #3DDB84

# yellow
color3  #FFCC66
color11 #FFCC66

# blue
color4  #7AA2F7
color12 #7AA2F7

# magenta
color5  #B18CFE
color13 #B18CFE

#cyan
color6  #97F1FB
color14 #97F1FB

#white
color7  #E0E2EA
color15 #E0E2EA

cursor #FFCC66
cursor_text_color #0B0E14
